name: Continuous integration tests

on: [ push, pull_request ]

jobs:
  phpunit:
    name: Unit tests (PHP ${{ matrix.php-versions }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions:
          - 7.2
          - 7.3
          - 7.4
          - 8.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: openssl, hash, gmp, xml
          tools: composer

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: "~/.composer/cache"
          key: "php${{ matrix.php-versions }}-composer-${{ hashFiles('**/composer.json') }}"
          restore-keys: "php${{ matrix.php-versions }}-composer-"

      - name: Install dependencies
        run: composer update && composer install

      - name: Run tests
        run: composer test

  stan:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: openssl, hash, gmp, xml
          tools: composer

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: "~/.composer/cache"
          key: "phpstan-composer-${{ hashFiles('**/composer.json') }}"
          restore-keys: "phpstan-composer-"

      - name: Install dependencies
        run: composer update && composer install

      - name: Perform static analysis
        run: composer phpstan
